#!/usr/bin/env node
// walkthrough-skill generator. Node >= 20, zero dependencies.
//
// Commands: init | refresh | check | build | dev | serve
// Flags:    --repo DIR   target repository root (default: inferred)
//           --base PATH  site base path for build/serve
// Env:      WALKTHROUGH_BASE, WALKTHROUGH_TZ
//
// Every template lives in this file as a string constant so that the copy
// vendored into <repo>/docs/walkthrough/bin/walkthrough.mjs runs standalone.

import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const GENERATOR = { name: 'walkthrough-skill', version: '1.0.0' };

const SITE = 'docs/walkthrough';
const SIDEBAR_BEGIN = '// walkthrough:sidebar:begin';
const SIDEBAR_END = '// walkthrough:sidebar:end';
const GENERATED_NOTE =
  '<!-- Generated by walkthrough-skill. Do not edit; run `walkthrough refresh`. -->';

const SCRIPTS = {
  'walkthrough:refresh': 'node docs/walkthrough/bin/walkthrough.mjs refresh',
  'walkthrough:check': 'node docs/walkthrough/bin/walkthrough.mjs check',
  'walkthrough:build': 'node docs/walkthrough/bin/walkthrough.mjs build',
  'walkthrough:dev': 'node docs/walkthrough/bin/walkthrough.mjs dev',
  'walkthrough:serve':
    'node docs/walkthrough/bin/walkthrough.mjs build && node docs/walkthrough/bin/walkthrough.mjs serve',
};

const VITEPRESS_VERSION = '^1.6.4';

// ---------------------------------------------------------------- templates

export const TPL_CONFIG_MTS = `import { defineConfig } from 'vitepress'

// walkthrough:sidebar:begin
{{SIDEBAR}}
// walkthrough:sidebar:end

export default defineConfig({
  title: '{{TITLE}}',
  description: '{{DESCRIPTION}}',
  base: '{{BASE}}',
  lastUpdated: true,
  cleanUrls: false,
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/reading-order' },
      { text: 'Areas', link: '{{AREAS_LINK}}' },
      { text: 'Generated', link: '/generated/inventory' },
    ],
    sidebar,
    outline: [2, 3],
    search: { provider: 'local' },
  },
})
`;

export const TPL_THEME_INDEX = `import DefaultTheme from 'vitepress/theme'
import Layout from './Layout.vue'

export default { extends: DefaultTheme, Layout }
`;

export const TPL_LAYOUT_VUE = `<script setup lang="ts">
import DefaultTheme from 'vitepress/theme'
import manifest from '../../manifest.json'

const { Layout } = DefaultTheme
const at = manifest.refreshedAt || {}
const root = manifest.root || {}
const subs = manifest.submodules || []
const stamp =
  'Walkthrough refreshed ' + at.local + ' (' + at.tz + ') at ' + root.short +
  ' on ' + root.branch + (root.dirty ? ' \\u00b7 dirty' : '')
</script>

<template>
  <Layout>
    <template #layout-bottom>
      <footer class="wt-stamp">
        <p class="wt-stamp-line">{{ stamp }}</p>
        <details v-if="subs.length" class="wt-stamp-subs">
          <summary>Submodules ({{ subs.length }})</summary>
          <ul>
            <li v-for="s in subs" :key="s.path">
              <code>{{ s.path }}</code> at <code>{{ s.sha.slice(0, 10) }}</code>
              <span v-if="s.branch"> ({{ s.branch }})</span>
            </li>
          </ul>
        </details>
      </footer>
    </template>
  </Layout>
</template>

<style scoped>
.wt-stamp {
  border-top: 1px solid var(--vp-c-divider);
  padding: 12px 24px 24px;
  font-size: 12px;
  color: var(--vp-c-text-2);
}
.wt-stamp-line { margin: 0 0 4px; font-family: var(--vp-font-family-mono); }
.wt-stamp-subs ul { margin: 4px 0 0; padding-left: 18px; }
</style>
`;

export const TPL_PAGE_INDEX = `---
title: {{TITLE}}
---

# {{TITLE}}

{{DESCRIPTION}}

## What it is

_Two to five plain sentences: what this repository produces, for whom, and what
it is not._

## Where things live

| Path | What is there | Read it when |
| --- | --- | --- |
| | | |

## How it runs

_The dev, test and build commands that actually exist in the root package.json.
Name the scripts exactly. One line per tier if the repository documents one._

## Boundaries and invariants

_What must stay true across the tree. Cite the ADR number or the AGENTS.md
section that says so._

## Start here

1. _file — why_

## Open questions / known rough edges

_Only what the tree evidences: TODO files, handoff notes, ADR status lines,
failing gates._

See [reading order](./guide/reading-order.md) and the
[generated inventory](./generated/inventory.md).
`;

export const TPL_PAGE_READING_ORDER = `---
title: Reading order
---

# Reading order

## What it is

_Where a newcomer starts, in order, and why each step earns its place._

## Where things live

| Step | Path | Why now |
| --- | --- | --- |
| 1 | | |

## How it runs

_The one command sequence that gets the tree running locally._

## Boundaries and invariants

_What a reader must believe before step 1 makes sense._

## Start here

1. _file — why_

## Open questions / known rough edges

_Steps that are currently painful, and what makes them painful._
`;

export const TPL_PAGE_TRAPS = `---
title: Traps
---

# Traps

## What it is

_Non-obvious invariants and things that look wrong but are not._

## Where things live

| Trap | Path | What to do instead |
| --- | --- | --- |
| | | |

## How it runs

_Commands that fail in a surprising way, and the correct invocation._

## Boundaries and invariants

_The rules whose violation causes the traps above._

## Start here

1. _file — why_

## Open questions / known rough edges

_Traps that are known but not yet fenced off in code._
`;

export const TPL_PAGE_GLOSSARY = `---
title: Glossary
---

# Glossary

## What it is

_The vocabulary of this repository and of the estate it runs in._

## Where things live

| Term | Means | Defined in |
| --- | --- | --- |
| | | |

## How it runs

_Where the names show up at runtime: script names, env vars, directory names._

## Boundaries and invariants

_Names that are load-bearing and must not be renamed casually._

## Start here

1. _file — why_

## Open questions / known rough edges

_Terms used inconsistently in the tree._
`;

export const TPL_PAGE_AREA = `---
title: {{AREA_NAME}}
---

# {{AREA_NAME}}

Kind: {{AREA_KIND}}. Path: \`{{AREA_PATH}}\`.

## What it is

_Two to five plain sentences for a newcomer._

## Where things live

| Path | What is there | Read it when |
| --- | --- | --- |
| | | |

## How it runs

_Dev, test, build and deploy commands that exist in this area. Cite the exact
script names._

## Boundaries and invariants

_What must stay true here. Cite the ADR number or AGENTS.md section._

## Start here

1. _file — why_

## Open questions / known rough edges

_Only what the tree evidences._
`;

// ---------------------------------------------------------------- utilities

function die(message, code = 1) {
  process.stderr.write(`walkthrough: ${message}\n`);
  process.exit(code);
}

function read(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

function writeFile(file, body) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
}

function writeIfAbsent(file, body) {
  if (fs.existsSync(file)) return false;
  writeFile(file, body);
  return true;
}

function fill(template, values) {
  return template.replace(/\{\{([A-Z_]+)\}\}/g, (whole, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : whole,
  );
}

function q(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function readJson(file) {
  const raw = read(file);
  if (raw === null) return null;
  try {
    return JSON.parse(raw);
  } catch (error) {
    die(`cannot parse ${file}: ${error.message}`);
  }
  return null;
}

function git(args, cwd) {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    maxBuffer: 1 << 28,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

function gitTry(args, cwd) {
  try {
    return git(args, cwd);
  } catch {
    return null;
  }
}

function table(header, rows) {
  const out = [`| ${header.join(' | ')} |`, `| ${header.map(() => '---').join(' | ')} |`];
  for (const row of rows) out.push(`| ${row.map((c) => String(c ?? '')).join(' | ')} |`);
  return out.join('\n');
}

function cell(value) {
  return String(value ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

// ---------------------------------------------------------------- repo model

function inferRepo() {
  const here = path.dirname(fileURLToPath(import.meta.url));
  if (path.basename(here) === 'bin' && path.basename(path.dirname(here)) === 'walkthrough') {
    return path.resolve(here, '../../..');
  }
  return process.cwd();
}

function parseArgs(argv) {
  const out = { command: null, repo: null, base: null, reset: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--repo') out.repo = argv[++i];
    else if (arg === '--base') out.base = argv[++i];
    else if (arg === '--reset-site') out.reset = true;
    else if (arg === '-h' || arg === '--help') out.command = 'help';
    else if (!out.command) out.command = arg;
  }
  return out;
}

function normaliseBase(base) {
  let value = String(base || '/').trim();
  if (!value.startsWith('/')) value = `/${value}`;
  if (!value.endsWith('/')) value = `${value}/`;
  return value.replace(/\/{2,}/g, '/');
}

function defaultConfig(repo) {
  const workspaces = [];
  for (const dir of ['apps', 'packages', 'services']) {
    if (fs.existsSync(path.join(repo, dir))) workspaces.push(`${dir}/*`);
  }
  const areas = [];
  for (const pattern of workspaces) {
    for (const pkgDir of expandWorkspace(repo, pattern)) {
      const slug = pkgDir.split('/').pop();
      areas.push({ slug, name: slug, kind: pattern.startsWith('apps') ? 'app' : 'package', path: pkgDir });
    }
  }
  for (const sub of listSubmodules(repo)) {
    if (areas.some((a) => a.path === sub.path)) continue;
    areas.push({ slug: sub.path.split('/').pop(), name: sub.path, kind: 'submodule', path: sub.path });
  }
  if (fs.existsSync(path.join(repo, 'scripts'))) {
    areas.push({ slug: 'tooling', name: 'Root tooling', kind: 'tooling', path: 'scripts' });
  }
  return {
    title: path.basename(repo),
    description: 'Codebase walkthrough.',
    base: '/',
    adrDir: 'docs/adr',
    workspaces,
    areas,
  };
}

function loadConfig(repo) {
  const file = path.join(repo, SITE, 'walkthrough.config.json');
  const parsed = readJson(file);
  if (!parsed) die(`missing ${SITE}/walkthrough.config.json — run \`init\` first`);
  const config = {
    title: parsed.title || path.basename(repo),
    description: parsed.description || '',
    base: normaliseBase(parsed.base || '/'),
    adrDir: parsed.adrDir || 'docs/adr',
    workspaces: Array.isArray(parsed.workspaces) ? parsed.workspaces : [],
    areas: Array.isArray(parsed.areas) ? parsed.areas : [],
  };
  for (const area of config.areas) {
    if (!area.slug || !area.path) die(`config area missing slug or path: ${JSON.stringify(area)}`);
    area.kind = area.kind || 'package';
    area.name = area.name || area.slug;
  }
  return config;
}

// Only simple `dir/*` globs, per contract.
function expandWorkspace(repo, pattern) {
  const found = [];
  if (!pattern.endsWith('/*')) {
    if (fs.existsSync(path.join(repo, pattern, 'package.json'))) found.push(pattern);
    return found;
  }
  const dir = pattern.slice(0, -2);
  let entries = [];
  try {
    entries = fs.readdirSync(path.join(repo, dir), { withFileTypes: true });
  } catch {
    return found;
  }
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
    const rel = `${dir}/${entry.name}`;
    if (fs.existsSync(path.join(repo, rel, 'package.json'))) found.push(rel);
  }
  return found;
}

function workspacePackages(repo, config) {
  const dirs = [];
  for (const pattern of config.workspaces) {
    for (const rel of expandWorkspace(repo, pattern)) if (!dirs.includes(rel)) dirs.push(rel);
  }
  return dirs.map((rel) => ({ rel, pkg: readJson(path.join(repo, rel, 'package.json')) || {} }));
}

function gitmodulesAt(repo, levelRel) {
  const file = path.join(repo, levelRel, '.gitmodules');
  if (!fs.existsSync(file)) return [];
  const raw = gitTry(['config', '-f', file, '--get-regexp', '^submodule\\.'], repo);
  if (!raw) return [];
  const byName = new Map();
  for (const line of raw.split('\n')) {
    const match = /^submodule\.(.+)\.(path|url|branch)\s+(.*)$/.exec(line.trim());
    if (!match) continue;
    const [, name, key, value] = match;
    if (!byName.has(name)) byName.set(name, { name });
    byName.get(name)[key] = value;
  }
  return [...byName.values()];
}

function listSubmodules(repo) {
  const raw = gitTry(['submodule', 'status', '--recursive'], repo);
  if (!raw) return [];
  const states = { ' ': 'ok', '-': 'not-initialised', '+': 'sha-differs', 'U': 'conflict' };
  const entries = [];
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    const flag = line[0] === ' ' ? ' ' : line[0];
    const rest = (line[0] === ' ' ? line.slice(1) : line.slice(1)).trim();
    const match = /^([0-9a-f]{40})\s+(\S+)(?:\s+\((.*)\))?$/.exec(rest);
    if (!match) continue;
    entries.push({
      path: match[2],
      sha: match[1],
      describe: match[3] || '',
      state: states[flag] || 'unknown',
    });
  }
  entries.sort((a, b) => a.path.localeCompare(b.path));
  const paths = entries.map((e) => e.path);
  return entries.map((entry) => {
    const parents = paths.filter((p) => p !== entry.path && entry.path.startsWith(`${p}/`));
    parents.sort((a, b) => b.length - a.length);
    const level = parents[0] || '';
    const within = level ? entry.path.slice(level.length + 1) : entry.path;
    const declared = gitmodulesAt(repo, level).find((m) => m.path === within) || {};
    return {
      path: entry.path,
      sha: entry.sha,
      url: declared.url || '',
      branch: declared.branch || '',
      depth: parents.length + 1,
      state: entry.state,
    };
  });
}

function rootState(repo) {
  const sha = gitTry(['rev-parse', 'HEAD'], repo);
  if (!sha) die('not a git repository (or no commits yet)');
  const branch = (gitTry(['rev-parse', '--abbrev-ref', 'HEAD'], repo) || '').trim();
  const dirty = (gitTry(['status', '--porcelain'], repo) || '').trim().length > 0;
  const full = sha.trim();
  return { sha: full, short: full.slice(0, 10), branch: branch || 'HEAD', dirty };
}

function stamp() {
  const tz =
    process.env.WALKTHROUGH_TZ ||
    process.env.TZ ||
    Intl.DateTimeFormat().resolvedOptions().timeZone ||
    'UTC';
  const now = new Date();
  const utc = `${now.toISOString().slice(0, 19)}Z`;
  let local = utc;
  try {
    const parts = new Intl.DateTimeFormat('en-CA', {
      timeZone: tz,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZoneName: 'short',
    }).formatToParts(now);
    const get = (type) => (parts.find((p) => p.type === type) || {}).value || '';
    local = `${get('year')}-${get('month')}-${get('day')} ${get('hour')}:${get('minute')} ${get('timeZoneName')}`;
  } catch {
    local = utc;
  }
  return { utc, local, tz };
}

// ---------------------------------------------------------------- generated

function pageInventory(repo, config) {
  const rows = config.areas.map((area) => {
    const abs = path.join(repo, area.path);
    const pkg = readJson(path.join(abs, 'package.json')) || {};
    const scripts = Object.keys(pkg.scripts || {});
    return [
      area.name,
      `\`${area.path}\``,
      area.kind,
      pkg.name ? `\`${pkg.name}\`` : '—',
      cell(pkg.description || (fs.existsSync(abs) ? '' : 'path missing in this checkout')),
      scripts.length ? scripts.slice(0, 8).join(', ') + (scripts.length > 8 ? ', …' : '') : '—',
    ];
  });
  return [
    GENERATED_NOTE,
    '# Inventory',
    '',
    `${config.areas.length} configured area(s).`,
    '',
    table(['Area', 'Path', 'Kind', 'Package', 'Description', 'Scripts'], rows),
    '',
  ].join('\n');
}

function pageSubmodules(subs) {
  const body = subs.length
    ? table(
        ['Path', 'Depth', 'Pinned', 'Branch', 'URL', 'Checkout'],
        subs.map((s) => [
          `\`${s.path}\``,
          s.depth,
          `\`${s.sha.slice(0, 10)}\``,
          s.branch || '—',
          s.url ? `\`${cell(s.url)}\`` : '—',
          s.state,
        ]),
      )
    : 'No gitlinks in this repository.';
  return [GENERATED_NOTE, '# Submodules', '', `${subs.length} gitlink(s), all depths.`, '', body, ''].join('\n');
}

function pageScripts(repo, config) {
  const lines = [GENERATED_NOTE, '# Scripts', ''];
  const root = readJson(path.join(repo, 'package.json')) || {};
  const rootScripts = Object.entries(root.scripts || {});
  lines.push(`## Root (\`package.json\`)`, '');
  lines.push(
    rootScripts.length
      ? table(['Script', 'Command'], rootScripts.map(([k, v]) => [`\`${k}\``, `\`${cell(v)}\``]))
      : 'No root scripts.',
  );
  lines.push('');
  for (const { rel, pkg } of workspacePackages(repo, config)) {
    const entries = Object.entries(pkg.scripts || {});
    lines.push(`## ${pkg.name || rel}`, '', `Path: \`${rel}\``, '');
    lines.push(
      entries.length
        ? table(['Script', 'Command'], entries.map(([k, v]) => [`\`${k}\``, `\`${cell(v)}\``]))
        : 'No scripts.',
    );
    lines.push('');
  }
  return lines.join('\n');
}

function adrFiles(repo, config) {
  const dir = path.join(repo, config.adrDir);
  let names = [];
  try {
    names = fs.readdirSync(dir).filter((n) => n.endsWith('.md'));
  } catch {
    return [];
  }
  return names.sort().map((name) => {
    const body = read(path.join(dir, name)) || '';
    const heading = /^#\s+(.+)$/m.exec(body);
    const status = /^\s*(?:[-*]\s*)?(?:\*\*)?status(?:\*\*)?\s*[::]\s*(.+)$/im.exec(body);
    const number = (/^(\d+)/.exec(name) || [, ''])[1];
    return {
      file: `${config.adrDir}/${name}`,
      number,
      title: heading ? heading[1].trim() : name.replace(/\.md$/, ''),
      status: status ? status[1].trim() : '',
    };
  });
}

function pageAdrs(repo, config) {
  const adrs = adrFiles(repo, config);
  const body = adrs.length
    ? table(
        ['#', 'Title', 'Status', 'File'],
        adrs.map((a) => [a.number || '—', cell(a.title), cell(a.status) || '—', `\`${a.file}\``]),
      )
    : `No ADR files under \`${config.adrDir}\`.`;
  return [GENERATED_NOTE, '# ADRs', '', `${adrs.length} record(s) in \`${config.adrDir}\`.`, '', body, ''].join('\n');
}

function logFor(repo, range, pathspec) {
  const raw = gitTry(['log', '--no-merges', '--format=%h %s', range, '--', ...pathspec], repo);
  if (raw === null) return null;
  return raw.split('\n').filter((l) => l.trim());
}

function hasCommit(repo, sha, cwd) {
  return gitTry(['cat-file', '-e', `${sha}^{commit}`], cwd || repo) !== null;
}

function pageChanges(repo, config, previous, subs) {
  const lines = [GENERATED_NOTE, '# Changes since last refresh', ''];
  const prev = previous && previous.rootSha;
  if (!prev) {
    const now = rootState(repo);
    lines.push(`First refresh at ${now.short}; no baseline.`, '');
    return lines.join('\n');
  }
  if (!hasCommit(repo, prev)) {
    lines.push(`Previous root commit ${prev.slice(0, 10)} is not in the local store; no diff possible.`, '');
    return lines.join('\n');
  }
  const range = `${prev}..HEAD`;
  lines.push(`Range: \`${prev.slice(0, 10)}..HEAD\``, '');
  const covered = [];
  for (const area of config.areas) {
    covered.push(area.path);
    lines.push(`## ${area.name}`, '', `Path: \`${area.path}\``, '');
    const log = logFor(repo, range, [area.path]) || [];
    const stat = (gitTry(['diff', '--shortstat', range, '--', area.path], repo) || '').trim();
    lines.push(`${log.length} commit(s).${stat ? ` ${stat}` : ''}`, '');
    for (const entry of log.slice(0, 30)) lines.push(`- ${entry}`);
    if (log.length > 30) lines.push(`- … ${log.length - 30} more`);
    lines.push('');
  }
  lines.push('## Other (outside every configured area)', '');
  const exclude = covered.map((p) => `:(exclude)${p}`);
  const otherLog = logFor(repo, range, ['.', ...exclude]) || [];
  lines.push(`${otherLog.length} commit(s).`, '');
  for (const entry of otherLog.slice(0, 30)) lines.push(`- ${entry}`);
  if (otherLog.length > 30) lines.push(`- … ${otherLog.length - 30} more`);
  lines.push('');

  lines.push('## Submodule moves', '');
  const before = new Map((previous.submodules || []).map((s) => [s.path, s.sha]));
  let moved = 0;
  for (const sub of subs) {
    const was = before.get(sub.path);
    if (!was || was === sub.sha) continue;
    moved += 1;
    lines.push(`### \`${sub.path}\``, '', `\`${was.slice(0, 10)}\` -> \`${sub.sha.slice(0, 10)}\``, '');
    const cwd = path.join(repo, sub.path);
    if (!fs.existsSync(cwd)) {
      lines.push('Submodule is not checked out here; no log available.', '');
      continue;
    }
    if (!hasCommit(repo, was, cwd)) {
      lines.push('Baseline commit not in local store.', '');
      continue;
    }
    const log = (gitTry(['-C', cwd, 'log', '--no-merges', '--format=%h %s', `${was}..${sub.sha}`], repo) || '')
      .split('\n')
      .filter((l) => l.trim());
    lines.push(`${log.length} commit(s).`, '');
    for (const entry of log.slice(0, 30)) lines.push(`- ${entry}`);
    if (log.length > 30) lines.push(`- … ${log.length - 30} more`);
    lines.push('');
  }
  if (!moved) lines.push('No submodule pins moved.', '');

  lines.push('## ADR files added or removed', '');
  const names = (gitTry(['diff', '--name-status', range, '--', config.adrDir], repo) || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .filter((l) => /^[AD]\t/.test(l));
  if (!names.length) lines.push('None.', '');
  else {
    for (const line of names) {
      const [flag, file] = line.split('\t');
      lines.push(`- ${flag === 'A' ? 'added' : 'removed'} \`${file}\``);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function authoredPages(repo) {
  const siteAbs = path.join(repo, SITE);
  const out = [];
  const walk = (dir) => {
    let entries = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      const abs = path.join(dir, entry.name);
      const rel = path.relative(siteAbs, abs).split(path.sep).join('/');
      if (entry.isDirectory()) {
        if (['generated', 'node_modules', '.vitepress', 'bin'].includes(entry.name)) continue;
        walk(abs);
      } else if (entry.name.endsWith('.md') && !rel.startsWith('generated/')) {
        out.push({ rel, abs });
      }
    }
  };
  walk(siteAbs);
  return out;
}

const PATH_TOKEN = /^[A-Za-z0-9_.-]+(\/[A-Za-z0-9_.@-]+)+$/;

export function citationMisses(repo, body) {
  const misses = [];
  const seen = new Set();
  for (const match of body.matchAll(/`([^`\n]+)`/g)) {
    const token = match[1].trim();
    if (!token || /\s/.test(token) || !token.includes('/')) continue;
    if (token.startsWith('~') || token.startsWith('/') || token.includes('://')) continue;
    if (token.includes('node_modules')) continue;
    const bare = token.replace(/:\d+(-\d+)?$/, '').replace(/\/$/, '');
    if (!PATH_TOKEN.test(bare)) continue;
    if (seen.has(bare)) continue;
    seen.add(bare);
    if (!fs.existsSync(path.join(repo, bare))) misses.push(bare);
  }
  return misses;
}

function pageDrift(repo) {
  const lines = [GENERATED_NOTE, '# Drift', '', 'Cited repo paths on authored pages that do not resolve.', ''];
  let total = 0;
  for (const page of authoredPages(repo)) {
    const misses = citationMisses(repo, read(page.abs) || '');
    if (!misses.length) continue;
    total += misses.length;
    lines.push(`## \`${SITE}/${page.rel}\``, '');
    for (const miss of misses) lines.push(`- \`${miss}\` does not exist`);
    lines.push('');
  }
  if (!total) lines.push('Clean: every cited path resolves.', '');
  return { body: lines.join('\n'), total };
}

// ---------------------------------------------------------------- sidebar

function sidebarSource(config) {
  const areas = config.areas.length
    ? config.areas.map((a) => `      { text: ${q(a.name)}, link: '/areas/${a.slug}' },`).join('\n')
    : '';
  const generated = [
    ['Inventory', 'inventory'],
    ['Submodules', 'submodules'],
    ['Scripts', 'scripts'],
    ['ADRs', 'adrs'],
    ['Changes', 'changes'],
    ['Drift', 'drift'],
  ]
    .map(([text, slug]) => `      { text: '${text}', link: '/generated/${slug}' },`)
    .join('\n');
  return [
    'const sidebar = [',
    '  {',
    "    text: 'Guide',",
    '    items: [',
    "      { text: 'Overview', link: '/' },",
    "      { text: 'Reading order', link: '/guide/reading-order' },",
    "      { text: 'Traps', link: '/guide/traps' },",
    "      { text: 'Glossary', link: '/guide/glossary' },",
    '    ],',
    '  },',
    '  {',
    "    text: 'Areas',",
    '    items: [',
    areas,
    '    ],',
    '  },',
    '  {',
    "    text: 'Generated',",
    '    items: [',
    generated,
    '    ],',
    '  },',
    ']',
  ]
    .filter((line) => line !== '')
    .join('\n');
}

function rewriteSidebar(configFile, config) {
  const body = read(configFile);
  if (body === null) return false;
  const begin = body.indexOf(SIDEBAR_BEGIN);
  const end = body.indexOf(SIDEBAR_END);
  if (begin === -1 || end === -1 || end < begin) return false;
  const head = body.slice(0, begin + SIDEBAR_BEGIN.length);
  const tail = body.slice(end);
  fs.writeFileSync(configFile, `${head}\n${sidebarSource(config)}\n${tail}`);
  return true;
}

// ---------------------------------------------------------------- commands

function manifestFile(repo) {
  return path.join(repo, SITE, 'manifest.json');
}

function cmdRefresh(repo) {
  const config = loadConfig(repo);
  const root = rootState(repo);
  const subs = listSubmodules(repo);
  const old = readJson(manifestFile(repo));
  const previous = old
    ? {
        rootSha: old.root ? old.root.sha : null,
        refreshedAtUtc: old.refreshedAt ? old.refreshedAt.utc : null,
        submodules: old.submodules || [],
      }
    : null;

  const changes = pageChanges(repo, config, previous, subs);
  const drift = pageDrift(repo);
  const site = path.join(repo, SITE);
  writeFile(path.join(site, 'generated/inventory.md'), pageInventory(repo, config));
  writeFile(path.join(site, 'generated/submodules.md'), pageSubmodules(subs));
  writeFile(path.join(site, 'generated/scripts.md'), pageScripts(repo, config));
  writeFile(path.join(site, 'generated/adrs.md'), pageAdrs(repo, config));
  writeFile(path.join(site, 'generated/changes.md'), changes);
  writeFile(path.join(site, 'generated/drift.md'), drift.body);

  const manifest = {
    generator: { ...GENERATOR },
    refreshedAt: stamp(),
    root,
    submodules: subs.map((s) => ({
      path: s.path,
      sha: s.sha,
      url: s.url,
      branch: s.branch,
      depth: s.depth,
    })),
    previous: {
      rootSha: previous ? previous.rootSha : null,
      refreshedAtUtc: previous ? previous.refreshedAtUtc : null,
    },
  };
  writeFile(manifestFile(repo), `${JSON.stringify(manifest, null, 2)}\n`);

  const configFile = path.join(site, '.vitepress/config.mts');
  const rewrote = rewriteSidebar(configFile, config);

  process.stdout.write(
    [
      `refreshed ${config.title} at ${root.short} on ${root.branch}${root.dirty ? ' (dirty)' : ''}`,
      `areas: ${config.areas.length}  submodules: ${subs.length}  adrs: ${adrFiles(repo, config).length}`,
      `sidebar: ${rewrote ? 'rewritten' : 'markers not found, left alone'}`,
      `drift: ${drift.total === 0 ? 'clean' : `${drift.total} unresolved citation(s)`}`,
    ].join('\n') + '\n',
  );
  if (drift.total) process.stdout.write(`${drift.body.split('\n').slice(4).join('\n').trim()}\n`);
  return 0;
}

function cmdCheck(repo) {
  const manifest = readJson(manifestFile(repo));
  if (!manifest) {
    process.stdout.write('STALE . none -> unknown\n');
    return 1;
  }
  const root = rootState(repo);
  const lines = [];
  if (!manifest.root || manifest.root.sha !== root.sha) {
    const was = manifest.root ? manifest.root.short : 'none';
    lines.push(`STALE . ${was} -> ${root.short}`);
  }
  const live = new Map(listSubmodules(repo).map((s) => [s.path, s.sha]));
  for (const sub of manifest.submodules || []) {
    const now = live.get(sub.path);
    if (now === undefined) lines.push(`STALE ${sub.path} ${sub.sha.slice(0, 10)} -> absent`);
    else if (now !== sub.sha) lines.push(`STALE ${sub.path} ${sub.sha.slice(0, 10)} -> ${now.slice(0, 10)}`);
  }
  const known = new Set((manifest.submodules || []).map((s) => s.path));
  for (const [p, sha] of live) {
    if (!known.has(p)) lines.push(`STALE ${p} absent -> ${sha.slice(0, 10)}`);
  }
  if (lines.length) {
    process.stdout.write(`${lines.join('\n')}\n`);
    return 1;
  }
  process.stdout.write(`FRESH ${manifest.root.short}\n`);
  return 0;
}

function patchPackageJson(repo) {
  const file = path.join(repo, 'package.json');
  const pkg = readJson(file) || { name: path.basename(repo), private: true, version: '0.0.0' };
  pkg.scripts = pkg.scripts || {};
  const added = [];
  for (const [key, value] of Object.entries(SCRIPTS)) {
    if (!(key in pkg.scripts)) {
      pkg.scripts[key] = value;
      added.push(key);
    }
  }
  pkg.devDependencies = pkg.devDependencies || {};
  if (!('vitepress' in pkg.devDependencies)) {
    pkg.devDependencies.vitepress = VITEPRESS_VERSION;
    added.push('devDependencies.vitepress');
  }
  fs.writeFileSync(file, `${JSON.stringify(pkg, null, 2)}\n`);
  return added;
}

function cmdInit(repo, args) {
  const site = path.join(repo, SITE);
  const created = [];
  const configFile = path.join(site, 'walkthrough.config.json');
  if (!fs.existsSync(configFile)) {
    writeFile(configFile, `${JSON.stringify(defaultConfig(repo), null, 2)}\n`);
    created.push(`${SITE}/walkthrough.config.json`);
  }
  const config = loadConfig(repo);

  const self = fileURLToPath(import.meta.url);
  const vendored = path.join(site, 'bin/walkthrough.mjs');
  if (path.resolve(self) !== path.resolve(vendored)) {
    fs.mkdirSync(path.dirname(vendored), { recursive: true });
    fs.copyFileSync(self, vendored);
    fs.chmodSync(vendored, 0o755);
    created.push(`${SITE}/bin/walkthrough.mjs`);
  }

  const siteConfig = path.join(site, '.vitepress/config.mts');
  if (!fs.existsSync(siteConfig) || args.reset) {
    writeFile(
      siteConfig,
      fill(TPL_CONFIG_MTS, {
        SIDEBAR: sidebarSource(config),
        TITLE: config.title.replace(/'/g, "\\'"),
        DESCRIPTION: (config.description || '').replace(/'/g, "\\'"),
        BASE: config.base,
        AREAS_LINK: config.areas.length ? `/areas/${config.areas[0].slug}` : '/generated/inventory',
      }),
    );
    created.push(`${SITE}/.vitepress/config.mts`);
  }
  if (writeIfAbsent(path.join(site, '.vitepress/theme/index.ts'), TPL_THEME_INDEX)) {
    created.push(`${SITE}/.vitepress/theme/index.ts`);
  }
  if (writeIfAbsent(path.join(site, '.vitepress/theme/Layout.vue'), TPL_LAYOUT_VUE)) {
    created.push(`${SITE}/.vitepress/theme/Layout.vue`);
  }

  const pages = [
    ['index.md', fill(TPL_PAGE_INDEX, { TITLE: config.title, DESCRIPTION: config.description })],
    ['guide/reading-order.md', TPL_PAGE_READING_ORDER],
    ['guide/traps.md', TPL_PAGE_TRAPS],
    ['guide/glossary.md', TPL_PAGE_GLOSSARY],
  ];
  for (const area of config.areas) {
    pages.push([
      `areas/${area.slug}.md`,
      fill(TPL_PAGE_AREA, { AREA_NAME: area.name, AREA_KIND: area.kind, AREA_PATH: area.path }),
    ]);
  }
  for (const [rel, body] of pages) {
    if (writeIfAbsent(path.join(site, rel), body)) created.push(`${SITE}/${rel}`);
  }

  const added = patchPackageJson(repo);
  process.stdout.write(
    [
      created.length ? `created:\n${created.map((c) => `  ${c}`).join('\n')}` : 'created: nothing (all present)',
      added.length ? `package.json: added ${added.join(', ')}` : 'package.json: already wired',
      added.includes('devDependencies.vitepress')
        ? 'next: install dependencies so that node_modules/.bin/vitepress exists'
        : '',
    ]
      .filter(Boolean)
      .join('\n') + '\n',
  );
  return cmdRefresh(repo);
}

function vitepressBin(repo) {
  const bin = path.join(repo, 'node_modules/.bin/vitepress');
  if (!fs.existsSync(bin)) {
    process.stderr.write(
      `walkthrough: ${path.relative(repo, bin)} not found — install devDependencies (e.g. \`pnpm install\`) in ${repo}\n`,
    );
    process.exit(1);
  }
  return bin;
}

function resolveBase(repo, args) {
  if (args.base) return normaliseBase(args.base);
  if (process.env.WALKTHROUGH_BASE) return normaliseBase(process.env.WALKTHROUGH_BASE);
  return loadConfig(repo).base;
}

function runVitepress(repo, argv) {
  const result = spawnSync(vitepressBin(repo), argv, { cwd: repo, stdio: 'inherit' });
  return result.status === null ? 1 : result.status;
}

function cmdBuild(repo, args) {
  const base = resolveBase(repo, args);
  cmdCheck(repo);
  const status = runVitepress(repo, ['build', SITE, '--base', base]);
  if (status !== 0) return status;
  // Publish the stamp beside the pages: a host that serves this dist answers
  // `<base>manifest.json`, which is how a deploy proves WHICH commit is live
  // without scraping the footer.
  const dist = path.join(repo, SITE, '.vitepress/dist');
  fs.copyFileSync(path.join(repo, SITE, 'manifest.json'), path.join(dist, 'manifest.json'));
  return 0;
}

// `localhost` rather than the loopback literal: same binding, and this file
// lives in a public repository whose privacy gate rejects bare IP addresses.
const DEV_HOST = 'localhost';

function cmdDev(repo, args) {
  return runVitepress(repo, ['dev', SITE, '--host', DEV_HOST, '--port', '5180', '--base', resolveBase(repo, args)]);
}

function cmdServe(repo, args) {
  return runVitepress(repo, [
    'preview',
    SITE,
    '--host',
    DEV_HOST,
    '--port',
    '5181',
    '--base',
    resolveBase(repo, args),
  ]);
}

const USAGE = `walkthrough-skill ${GENERATOR.version} — generate a codebase walkthrough site

usage: node walkthrough.mjs <command> [--repo DIR] [--base PATH]

commands:
  init      scaffold docs/walkthrough/, vendor this script, wire package.json, refresh
  refresh   regenerate generated/*, manifest.json and the config sidebar region
  check     compare the stamp against HEAD and every submodule; exit 1 when stale
  build     vitepress build docs/walkthrough (base: --base > WALKTHROUGH_BASE > config)
  dev       vitepress dev on localhost:5180
  serve     vitepress preview on localhost:5181

flags:
  --repo DIR      target repository root (default: inferred from this script's location)
  --base PATH     site base path for build/dev/serve
  --reset-site    let init overwrite .vitepress/config.mts

env:
  WALKTHROUGH_BASE   base path fallback
  WALKTHROUGH_TZ     timezone used for the local stamp
`;

export function main(argv) {
  const args = parseArgs(argv);
  if (!args.command || args.command === 'help') {
    process.stdout.write(USAGE);
    return 2;
  }
  const repo = path.resolve(args.repo || inferRepo());
  if (!fs.existsSync(repo)) die(`no such directory: ${repo}`);
  switch (args.command) {
    case 'init':
      return cmdInit(repo, args);
    case 'refresh':
      return cmdRefresh(repo);
    case 'check':
      return cmdCheck(repo);
    case 'build':
      return cmdBuild(repo, args);
    case 'dev':
      return cmdDev(repo, args);
    case 'serve':
      return cmdServe(repo, args);
    default:
      process.stderr.write(`walkthrough: unknown command '${args.command}'\n\n${USAGE}`);
      return 2;
  }
}

// Node resolves the main module through symlinks, so import.meta.url is the
// realpath while process.argv[1] is whatever the caller typed (for example a
// ~/.agents/skills/walkthrough symlink). Compare realpaths or a symlinked
// invocation silently does nothing.
const invokedDirectly = (() => {
  if (!process.argv[1]) return false;
  try {
    return fs.realpathSync(fileURLToPath(import.meta.url)) === fs.realpathSync(process.argv[1]);
  } catch {
    return false;
  }
})();
if (invokedDirectly) process.exit(main(process.argv.slice(2)));
